include: package:flutter_lints/flutter.yaml

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list

  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
    number-of-methods: 10
    weight-of-class: 0.33
    maintainability-index: 50

  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else

analyzer:
  language:
    strict-casts: false
    strict-inference: true
    strict-raw-types: false
  exclude: [ build/**, "**/*.freezed.dart", "**/*.g.dart", "**/*.gr.dart", "**/*.gen.dart" ]

  errors:
    always_use_package_imports: error
    # Built-in rules
    body_might_complete_normally_nullable: error
    # Error rules
    avoid_dynamic_calls: error
    avoid_empty_else: error
    avoid_returning_null_for_future: error
    avoid_slow_async_io: error
    avoid_type_to_string: error
    cancel_subscriptions: error
    close_sinks: error
    empty_statements: error
    hash_and_equals: error
    iterable_contains_unrelated_type: error
    list_remove_unrelated_type: error

    # Style Rules
    always_declare_return_types: error
    always_put_control_body_on_new_line: error
    avoid_equals_and_hash_code_on_mutable_classes: error
    avoid_field_initializers_in_const_classes: error
    avoid_function_literals_in_foreach_calls: error
    avoid_returning_this: error
    avoid_unused_constructor_parameters: error
    avoid_void_async: error
    await_only_futures: error
    camel_case_extensions: error
    comment_references: error
    conditional_uri_does_not_exist: error
    curly_braces_in_flow_control_structures: error
    directives_ordering: warning
    empty_constructor_bodies: error
    empty_catches: error
    file_names: error
    implementation_imports: error
    no_leading_underscores_for_local_identifiers: error
    null_closures: error
    omit_local_variable_types: error
    package_api_docs: error
    package_prefixed_library_names: error
    prefer_adjacent_string_concatenation: error
    prefer_equal_for_default_values: error
    prefer_if_null_operators: error
    parameter_assignments: error
    prefer_asserts_with_message: error
    prefer_const_constructors: error
    prefer_const_constructors_in_immutables: error
    prefer_const_declarations: error
    prefer_const_literals_to_create_immutables: error
    prefer_expression_function_bodies: warning
    use_decorated_box: warning
    prefer_final_fields: error
    prefer_final_in_for_each: error
    prefer_final_locals: error
    prefer_function_declarations_over_variables: error
    prefer_generic_function_type_aliases: error
    prefer_initializing_formals: error
    prefer_typing_uninitialized_variables: error
    provide_deprecation_message: error
    recursive_getters: error
    tighten_type_of_initializing_formals: error
    type_annotate_public_apis: error
    unawaited_futures: error
    unnecessary_await_in_return: error
    unnecessary_this: error
    use_full_hex_values_for_flutter_colors: error
    use_function_type_syntax_for_parameters: error
    use_string_buffers: error
    use_enums: error
    use_key_in_widget_constructors: error
    use_rethrow_when_possible: error
    use_setters_to_change_properties: error
    use_to_and_as_if_applicable: error
    valid_regexps: error
    void_checks: error
    tearoff_of_generative_constructor_of_abstract_class: error
    prefer_spread_collections: error
    prefer_int_literals: error
    prefer_single_quotes: error
    prefer_is_empty: error
    prefer_is_not_empty: error
    prefer_iterable_whereType: error
    prefer_if_elements_to_conditional_expressions: error
    prefer_conditional_assignment: error
    # Pub Rules
    depend_on_referenced_packages: error
    secure_pubspec_urls: error
    read_potentially_unassigned_final: error
    # Flutter Rules
    avoid_web_libraries_in_flutter: error
    flutter_style_todos: error
    no_logic_in_create_state: error
    # Lint Rules
    avoid_as: error
    avoid_catches_without_on_clauses: error
    avoid_catching_errors: error
    avoid_classes_with_only_static_members: error
    avoid_double_and_int_checks: error
    avoid_implementing_value_types: error
    avoid_init_to_null: error
    avoid_js_rounded_ints: error
    avoid_null_checks_in_equality_operators: error
    avoid_positional_boolean_parameters: warning
    avoid_print: warning
    avoid_private_typedef_functions: error
    binary_operator_written_out: error
    body_might_complete_normally: error
    diagnostic_describe_all_properties: error
    cast_nullable_to_non_nullable: error
    avoid_redundant_argument_values: error
    avoid_relative_lib_imports: error
    use_test_throws_matchers: error
    use_named_constants: error
    use_is_even_rather_than_modulo: error
    use_if_null_to_convert_nulls_to_bools: error
    use_colored_box: error
    use_build_context_synchronously: error
    unnecessary_cast: error
    unnecessary_type_check: error
    unnecessary_string_interpolations: error
    unnecessary_string_escapes: error
    unnecessary_raw_strings: error
    unnecessary_nullable_for_final_variable_declarations: error
    unnecessary_null_checks: error
    unnecessary_late: error
    unnecessary_constructor_name: error
    sort_child_properties_last: error
    slash_for_doc_comments: error
    sized_box_shrink_expand: error
    sized_box_for_whitespace: error
    sort_pub_dependencies: error
    throw_in_finally: error
    unnecessary_statements: error
    unrelated_type_equality_checks: error
    unsafe_html: error
    prefer_void_to_null: error
    cascade_invocations: error
    overridden_fields: error
    prefer_inlined_adds: error
    avoid_unnecessary_containers: error
    always_require_non_null_named_parameters: error
    annotate_overrides: error
    only_throw_errors: error
    argument_type_not_assignable: warning
    unnecessary_const: error
    type_init_formals: error
    prefer_is_not_operator: error
    prefer_interpolation_to_compose_strings: error
    prefer_foreach: error
    prefer_for_elements_to_map_fromIterable: error
    prefer_contains: error
    null_check_on_nullable_type_parameter: error
    non_constant_identifier_names: error
    library_private_types_in_public_api: error
    avoid_types_as_parameter_names: error
    collection_methods_unrelated_type: error
    deprecated_member_use_from_same_package: error
    discarded_futures: error
    literal_only_boolean_expressions: error
    no_adjacent_strings_in_list: error
    no_duplicate_case_values: error
    prefer_relative_imports: error
    sort_unnamed_constructors_first: error
    prefer_constructors_over_static_methods: error
    sort_constructors_first: error

linter:
  rules:
    - sort_constructors_first
    - implementation_imports
    - library_private_types_in_public_api
    - null_check_on_nullable_type_parameter
    - null_closures
    - prefer_contains
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_if_null_operators
    - prefer_interpolation_to_compose_strings
    - prefer_is_not_operator
    - depend_on_referenced_packages
    - only_throw_errors
    - avoid_unnecessary_containers
    - prefer_inlined_adds
    - use_decorated_box
    - cascade_invocations
    - overridden_fields
    - unsafe_html
    - prefer_void_to_null
    - unrelated_type_equality_checks
    - avoid_types_on_closure_parameters
    - avoid_void_async
    - directives_ordering
    - package_api_docs
    - package_prefixed_library_names
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_breaks
    - unnecessary_statements
    - use_super_parameters
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - valid_regexps
    - avoid_annotating_with_dynamic
    - avoid_as
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_init_to_null
    - avoid_js_rounded_ints
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_print
    - avoid_private_typedef_functions
    - avoid_return_types_on_setters
    - avoid_returning_null_for_future
    - avoid_returning_null
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_single_cascade_in_expression_statements
    - await_only_futures
    - camel_case_extensions
    - comment_references
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_logic_in_create_state
    - no_runtimeType_toString
    - non_constant_identifier_names
    - prefer_adjacent_string_concatenation
    - prefer_asserts_with_message
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_initializing_formals
    - prefer_int_literals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - recursive_getters
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - type_init_formals
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_key_in_widget_constructors
    - void_checks
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - cast_nullable_to_non_nullable
    - parameter_assignments
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - use_test_throws_matchers
    - use_named_constants
    - use_is_even_rather_than_modulo
    - use_if_null_to_convert_nulls_to_bools
    - use_colored_box
    - use_build_context_synchronously
    - unnecessary_string_interpolations
    - unnecessary_string_escapes
    - unnecessary_raw_strings
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_null_checks
    - unnecessary_late
    - unnecessary_constructor_name
    - sort_child_properties_last
    - slash_for_doc_comments
    - sized_box_shrink_expand
    - sized_box_for_whitespace
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers