#!/usr/bin/env bash
# Typechecks the plugin's Kotlin sources with the Kotlin compiler from the Gradle
# cache — no Gradle, no example app build. R and ViewBinding classes are stubbed
# from res/. Usage: typecheck.sh [kotlin-src-dir]   (default: android/src/main/kotlin)
set -euo pipefail

ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
SRC="${1:-$ROOT/android/src/main/kotlin}"
RES="$ROOT/android/src/main/res"
M="$HOME/.gradle/caches/modules-2/files-2.1"
WORK="${TMPDIR:-/tmp}/video_player_android_typecheck"
mkdir -p "$WORK/libs" "$WORK/stubs"

KOTLIN_VERSION="$(ls "$M/org.jetbrains.kotlin/kotlin-compiler-embeddable" 2>/dev/null | sort -V | tail -1)"
MEDIA3_VERSION="$(grep -o 'media3Version = "[^"]*"' "$ROOT/android/build.gradle.kts" | cut -d'"' -f2)"
ANDROID_JAR="$(ls -d "$HOME"/Library/Android/sdk/platforms/android-* 2>/dev/null | sort -V | tail -1)/android.jar"
if [[ -z "$KOTLIN_VERSION" || ! -f "$ANDROID_JAR" ]]; then
  echo "Kotlin compiler or Android SDK not found in the Gradle cache / SDK." >&2
  echo "The project must have been built once on this machine — ask the user before building." >&2
  exit 1
fi

jar_of() { find "$M/$1" -name '*.jar' ! -name '*sources*' ! -name '*javadoc*' 2>/dev/null | sort -V | tail -1; }
COMPILER_CP="$(jar_of org.jetbrains.kotlin/kotlin-compiler-embeddable/$KOTLIN_VERSION):$(jar_of org.jetbrains.kotlin/kotlin-stdlib/$KOTLIN_VERSION):$(jar_of org.jetbrains.kotlin/kotlin-script-runtime/$KOTLIN_VERSION):$(jar_of org.jetbrains.kotlin/kotlin-reflect):$(jar_of org.jetbrains.kotlin/kotlin-daemon-embeddable/$KOTLIN_VERSION):$(jar_of org.jetbrains.intellij.deps/trove4j):$(jar_of org.jetbrains.kotlinx/kotlinx-coroutines-core-jvm):$(jar_of org.jetbrains/annotations)"

# 1. Library classes: newest stable version of each cached artifact (media3 pinned to build.gradle.kts).
if [[ ! -f "$WORK/libs/.media3-$MEDIA3_VERSION" ]]; then
  rm -f "$WORK/libs/"*.jar
  python3 - "$M" "$WORK/libs" "$MEDIA3_VERSION" <<'PY'
import os, re, sys, zipfile
M, out, media3 = sys.argv[1:4]
groups = ('com.google.android.material', 'com.google.code.gson', 'com.google.guava', 'org.jetbrains.kotlinx', 'org.jspecify')
key = lambda v: [int(x) if x.isdigit() else -1 for x in re.split(r'[.\-]', v)]
for group in os.listdir(M):
    if not (group.startswith('androidx.') or group in groups):
        continue
    for art in os.listdir(os.path.join(M, group)):
        versions = os.listdir(os.path.join(M, group, art))
        if group == 'androidx.media3':
            versions = [v for v in versions if v == media3] or versions
        versions = [v for v in versions if not re.search(r'alpha|beta|rc', v, re.I)] or versions
        v = max(versions, key=key)
        for root, _, files in os.walk(os.path.join(M, group, art, v)):
            for f in files:
                src, dst = os.path.join(root, f), os.path.join(out, f'{group}__{art}__{v}.jar')
                if f.endswith('.aar'):
                    with zipfile.ZipFile(src) as z:
                        if 'classes.jar' in z.namelist():
                            open(dst, 'wb').write(z.read('classes.jar'))
                elif f.endswith('.jar') and 'sources' not in f and 'javadoc' not in f:
                    open(dst, 'wb').write(open(src, 'rb').read())
PY
  touch "$WORK/libs/.media3-$MEDIA3_VERSION"
fi

# 2. Stub R and ViewBinding classes from res/ (normally generated by AGP).
python3 - "$RES" "$WORK/stubs" <<'PY'
import os, sys, xml.etree.ElementTree as ET
res, out = sys.argv[1:3]
A = '{http://schemas.android.com/apk/res/android}'
camel = lambda s: (lambda p: p[0] + ''.join(x[:1].upper() + x[1:] for x in p[1:]))(s.split('_'))
def cls(tag):
    if '.' in tag: return tag
    return ('android.view.' if tag in ('View', 'ViewGroup', 'SurfaceView', 'TextureView', 'ViewStub') else 'android.widget.') + tag
r = {k: set() for k in ('id', 'layout', 'drawable', 'string', 'style', 'color', 'dimen')}
bindings = []
for f in sorted(os.listdir(os.path.join(res, 'layout'))):
    name, root = f[:-4], ET.parse(os.path.join(res, 'layout', f)).getroot()
    r['layout'].add(name)
    fields = []
    for el in root.iter():
        i = el.get(A + 'id') or ''
        if i.startswith('@+id/'):
            r['id'].add(i[5:])
            if el.tag not in ('include', 'merge'):
                fields.append((camel(i[5:]), cls(el.tag)))
    bindings.append((''.join(x.capitalize() for x in name.split('_')) + 'Binding', cls(root.tag), fields))
for d in os.listdir(res):
    path = os.path.join(res, d)
    if d.startswith('drawable') or d.startswith('mipmap'):
        r['drawable'].update(f.split('.')[0] for f in os.listdir(path))
    elif d.startswith('values'):
        for f in os.listdir(path):
            for e in ET.parse(os.path.join(path, f)).getroot():
                if e.get('name') and e.tag in r:
                    r[e.tag].add(e.get('name').replace('.', '_'))
with open(os.path.join(out, 'R.kt'), 'w') as fh:
    fh.write('package uz.plugin.video_player\n\nobject R {\n')
    for k, names in r.items():
        fh.write(f'    object {k} {{\n' + ''.join(f'        const val {n} = 0\n' for n in sorted(names)) + '    }\n')
    fh.write('}\n')
with open(os.path.join(out, 'Bindings.kt'), 'w') as fh:
    fh.write('package uz.plugin.video_player.databinding\n\nimport android.view.LayoutInflater\nimport android.view.View\n\n')
    for n, root, fields in bindings:
        fh.write(f'class {n} {{\n    val root: {root} get() = TODO()\n')
        fh.writelines(f'    val {fn}: {t} get() = TODO()\n' for fn, t in fields)
        fh.write(f'    companion object {{\n        fun inflate(inflater: LayoutInflater): {n} = TODO()\n'
                 f'        fun bind(view: View): {n} = TODO()\n    }}\n}}\n\n')
PY

# 3. Compile.
FLUTTER_EMBEDDING="$(ls -t $(find "$M/io.flutter/flutter_embedding_debug" -name '*.jar' ! -name '*sources*') | head -1)"
CLASSPATH="$ANDROID_JAR:$FLUTTER_EMBEDDING:$(jar_of org.jetbrains.kotlin/kotlin-stdlib/$KOTLIN_VERSION):$(ls "$WORK"/libs/*.jar | tr '\n' ':')"
rm -rf "$WORK/out"
# shellcheck disable=SC2046
if java -cp "$COMPILER_CP" org.jetbrains.kotlin.cli.jvm.K2JVMCompiler -no-stdlib -no-reflect -jvm-target 17 \
    -Xskip-prerelease-check -nowarn -cp "$CLASSPATH" -d "$WORK/out" \
    $(find "$SRC" -name '*.kt') "$WORK/stubs/R.kt" "$WORK/stubs/Bindings.kt"; then
  echo "Android: OK"
else
  exit 1
fi
